# Generated by Django 3.0.8 on 2020-07-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20200724_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folders',
            field=models.ManyToManyField(related_name='parents', to='src.Folder'),
        ),
    ]
