# Generated by Django 3.0.8 on 2020-07-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_file_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='doc_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
